import 'package:flutter/material.dart';
import 'package:intl/intl.dart';
import 'package:petshopapp/core/theme/app_colors.dart';
import 'package:petshopapp/models/order_model.dart';
import 'package:petshopapp/models/product_model.dart';
import 'package:petshopapp/services/firestore_service.dart';

class AdminPosScreen extends StatefulWidget {
  const AdminPosScreen({super.key});

  @override
  State<AdminPosScreen> createState() => _AdminPosScreenState();
}

class _AdminPosScreenState extends State<AdminPosScreen> {
  final currencyFormatter = NumberFormat.currency(locale: 'id_ID', symbol: 'Rp ', decimalDigits: 0);
  
  // Local cart for POS
  final Map<String, int> _cart = {}; // productId -> quantity
  List<ProductModel> _allProducts = [];
  
  String _searchQuery = '';
  
  // Payment calculations
  double _uangDiterima = 0;
  final TextEditingController _paymentController = TextEditingController();

  @override
  void dispose() {
    _paymentController.dispose();
    super.dispose();
  }

  void _addToCart(ProductModel product) {
    if (product.stok <= 0) {
      ScaffoldMessenger.of(context).showSnackBar(const SnackBar(content: Text('Stok habis!')));
      return;
    }
    setState(() {
      final currentQty = _cart[product.productId] ?? 0;
      if (currentQty < product.stok) {
        _cart[product.productId] = currentQty + 1;
      } else {
        ScaffoldMessenger.of(context).showSnackBar(const SnackBar(content: Text('Stok tidak mencukupi!')));
      }
    });
  }

  void _removeFromCart(String productId) {
    setState(() {
      final currentQty = _cart[productId] ?? 0;
      if (currentQty > 1) {
        _cart[productId] = currentQty - 1;
      } else {
        _cart.remove(productId);
      }
    });
  }
  
  void _deleteFromCart(String productId) {
    setState(() {
      _cart.remove(productId);
    });
  }

  double _calculateTotal() {
    double total = 0;
    for (var entry in _cart.entries) {
      final product = _allProducts.firstWhere((p) => p.productId == entry.key);
      total += product.harga * entry.value;
    }
    return total;
  }

  Future<void> _processCheckout() async {
    final total = _calculateTotal();
    
    if (_cart.isEmpty) {
      ScaffoldMessenger.of(context).showSnackBar(const SnackBar(content: Text('Keranjang masih kosong!')));
      return;
    }

    if (_uangDiterima < total) {
      ScaffoldMessenger.of(context).showSnackBar(const SnackBar(content: Text('Uang diterima kurang dari total belanja!')));
      return;
    }

    // Build Order Items
    List<OrderItemModel> orderItems = [];
    for (var entry in _cart.entries) {
      final product = _allProducts.firstWhere((p) => p.productId == entry.key);
      orderItems.add(OrderItemModel(
        productId: product.productId,
        nama: product.namaProduk,
        jumlah: entry.value,
        hargaSatuan: product.harga,
      ));
    }

    // Create Order Model
    final order = OrderModel(
      orderId: '', // Generated by Firestore
      customerId: 'OFFLINE_CUSTOMER', // Special ID for offline walk-in customers
      items: orderItems,
      totalHarga: total,
      statusBayar: 'Lunas',
      statusPengiriman: 'Selesai', // Directly finished since it's offline
      metodePengambilan: 'Offline',
      metodePembayaran: 'Tunai',
      createdAt: DateTime.now(),
    );

    try {
      showDialog(
        context: context,
        barrierDismissible: false,
        builder: (context) => const Center(child: CircularProgressIndicator()),
      );
      
      await FirestoreService.instance.createOrder(order);
      
      if (mounted) {
        Navigator.pop(context); // Close loading dialog
        
        final kembalian = _uangDiterima - total;
        _showSuccessDialog(kembalian);
        
        setState(() {
          _cart.clear();
          _uangDiterima = 0;
          _paymentController.clear();
        });
      }
    } catch (e) {
      if (mounted) {
        Navigator.pop(context);
        ScaffoldMessenger.of(context).showSnackBar(SnackBar(content: Text('Error: $e')));
      }
    }
  }

  void _showSuccessDialog(double kembalian) {
    showDialog(
      context: context,
      builder: (context) => AlertDialog(
        title: const Row(
          children: [
            Icon(Icons.check_circle, color: Colors.green, size: 30),
            SizedBox(width: 10),
            Text('Transaksi Berhasil!'),
          ],
        ),
        content: Column(
          mainAxisSize: MainAxisSize.min,
          crossAxisAlignment: CrossAxisAlignment.start,
          children: [
            const Text('Pembayaran kasir offline telah dicatat.'),
            const SizedBox(height: 16),
            Text('Total Uang Kembalian:', style: TextStyle(color: Colors.grey[700])),
            Text(currencyFormatter.format(kembalian), style: const TextStyle(fontSize: 24, fontWeight: FontWeight.bold, color: AppColors.primary)),
          ],
        ),
        actions: [
          ElevatedButton(
            onPressed: () => Navigator.pop(context),
            style: ElevatedButton.styleFrom(backgroundColor: AppColors.primary, foregroundColor: Colors.white),
            child: const Text('Tutup'),
          ),
        ],
      ),
    );
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      backgroundColor: AppColors.background,
      body: Padding(
        padding: const EdgeInsets.all(16.0),
        child: Row(
          children: [
            // LEFT SIDE: Product List
            Expanded(
              flex: 2,
              child: Container(
                decoration: BoxDecoration(
                  color: Colors.white,
                  borderRadius: BorderRadius.circular(16),
                  boxShadow: [
                    BoxShadow(color: Colors.black.withOpacity(0.05), blurRadius: 10, offset: const Offset(0, 4)),
                  ],
                ),
                child: Column(
                  children: [
                    // Search Bar
                    Padding(
                      padding: const EdgeInsets.all(16.0),
                      child: TextField(
                        decoration: InputDecoration(
                          hintText: 'Cari Produk...',
                          prefixIcon: const Icon(Icons.search),
                          border: OutlineInputBorder(
                            borderRadius: BorderRadius.circular(12),
                            borderSide: BorderSide(color: Colors.grey.shade300),
                          ),
                          filled: true,
                          fillColor: Colors.grey.shade50,
                        ),
                        onChanged: (val) {
                          setState(() {
                            _searchQuery = val.toLowerCase();
                          });
                        },
                      ),
                    ),
                    
                    // Product Grid
                    Expanded(
                      child: StreamBuilder<List<ProductModel>>(
                        stream: FirestoreService.instance.getProductsStream(),
                        builder: (context, snapshot) {
                          if (snapshot.connectionState == ConnectionState.waiting) {
                            return const Center(child: CircularProgressIndicator());
                          }
                          if (snapshot.hasError) {
                            return Center(child: Text('Error: ${snapshot.error}'));
                          }
                          
                          _allProducts = snapshot.data ?? [];
                          
                          // Filter products
                          final filteredProducts = _allProducts.where((p) => p.namaProduk.toLowerCase().contains(_searchQuery)).toList();
                          
                          if (filteredProducts.isEmpty) {
                            return const Center(child: Text('Produk tidak ditemukan.'));
                          }

                          return GridView.builder(
                            padding: const EdgeInsets.symmetric(horizontal: 16, vertical: 8),
                            gridDelegate: const SliverGridDelegateWithFixedCrossAxisCount(
                              crossAxisCount: 3,
                              childAspectRatio: 0.75,
                              crossAxisSpacing: 16,
                              mainAxisSpacing: 16,
                            ),
                            itemCount: filteredProducts.length,
                            itemBuilder: (context, index) {
                              final product = filteredProducts[index];
                              final isOutOfStock = product.stok <= 0;
                              
                              return InkWell(
                                onTap: isOutOfStock ? null : () => _addToCart(product),
                                child: Container(
                                  decoration: BoxDecoration(
                                    border: Border.all(color: Colors.grey.shade200),
                                    borderRadius: BorderRadius.circular(12),
                                  ),
                                  child: Stack(
                                    children: [
                                      Column(
                                        crossAxisAlignment: CrossAxisAlignment.stretch,
                                        children: [
                                          Expanded(
                                            child: ClipRRect(
                                              borderRadius: const BorderRadius.vertical(top: Radius.circular(12)),
                                              child: product.fotoUrl.isNotEmpty
                                                  ? Image.network(product.fotoUrl, fit: BoxFit.cover)
                                                  : Container(color: Colors.grey.shade200, child: const Icon(Icons.image, color: Colors.grey)),
                                            ),
                                          ),
                                          Padding(
                                            padding: const EdgeInsets.all(8.0),
                                            child: Column(
                                              crossAxisAlignment: CrossAxisAlignment.start,
                                              children: [
                                                Text(product.namaProduk, maxLines: 2, overflow: TextOverflow.ellipsis, style: const TextStyle(fontWeight: FontWeight.bold, fontSize: 13)),
                                                const SizedBox(height: 4),
                                                Text(currencyFormatter.format(product.harga), style: const TextStyle(color: AppColors.primary, fontWeight: FontWeight.bold)),
                                                const SizedBox(height: 4),
                                                Text('Stok: ${product.stok}', style: TextStyle(color: isOutOfStock ? Colors.red : Colors.grey, fontSize: 12)),
                                              ],
                                            ),
                                          ),
                                        ],
                                      ),
                                      if (isOutOfStock)
                                        Container(
                                          decoration: BoxDecoration(
                                            color: Colors.white.withOpacity(0.7),
                                            borderRadius: BorderRadius.circular(12),
                                          ),
                                          alignment: Alignment.center,
                                          child: const Text('HABIS', style: TextStyle(color: Colors.red, fontWeight: FontWeight.bold, fontSize: 18)),
                                        ),
                                    ],
                                  ),
                                ),
                              );
                            },
                          );
                        },
                      ),
                    ),
                  ],
                ),
              ),
            ),
            
            const SizedBox(width: 16),
            
            // RIGHT SIDE: Cart & Payment
            Expanded(
              flex: 1,
              child: Container(
                decoration: BoxDecoration(
                  color: Colors.white,
                  borderRadius: BorderRadius.circular(16),
                  boxShadow: [
                    BoxShadow(color: Colors.black.withOpacity(0.05), blurRadius: 10, offset: const Offset(0, 4)),
                  ],
                ),
                child: Column(
                  children: [
                    Container(
                      width: double.infinity,
                      padding: const EdgeInsets.all(16),
                      decoration: const BoxDecoration(
                        color: AppColors.primary,
                        borderRadius: BorderRadius.vertical(top: Radius.circular(16)),
                      ),
                      child: const Text('Keranjang Kasir', style: TextStyle(color: Colors.white, fontSize: 18, fontWeight: FontWeight.bold)),
                    ),
                    
                    // Cart Items
                    Expanded(
                      child: _cart.isEmpty
                          ? Center(
                              child: Column(
                                mainAxisAlignment: MainAxisAlignment.center,
                                children: [
                                  Icon(Icons.shopping_cart_outlined, size: 64, color: Colors.grey.shade300),
                                  const SizedBox(height: 16),
                                  Text('Keranjang masih kosong', style: TextStyle(color: Colors.grey.shade500)),
                                ],
                              ),
                            )
                          : ListView.builder(
                              itemCount: _cart.length,
                              itemBuilder: (context, index) {
                                final productId = _cart.keys.elementAt(index);
                                final quantity = _cart[productId]!;
                                final product = _allProducts.firstWhere((p) => p.productId == productId);
                                
                                return ListTile(
                                  title: Text(product.namaProduk, maxLines: 1, overflow: TextOverflow.ellipsis),
                                  subtitle: Text('${currencyFormatter.format(product.harga)} x $quantity'),
                                  trailing: Row(
                                    mainAxisSize: MainAxisSize.min,
                                    children: [
                                      IconButton(
                                        icon: const Icon(Icons.remove_circle_outline, color: Colors.red),
                                        onPressed: () => _removeFromCart(productId),
                                      ),
                                      Text('$quantity', style: const TextStyle(fontWeight: FontWeight.bold, fontSize: 16)),
                                      IconButton(
                                        icon: const Icon(Icons.add_circle_outline, color: AppColors.primary),
                                        onPressed: () => _addToCart(product),
                                      ),
                                    ],
                                  ),
                                );
                              },
                            ),
                    ),
                    
                    // Payment Section
                    Container(
                      padding: const EdgeInsets.all(16),
                      decoration: BoxDecoration(
                        color: Colors.grey.shade50,
                        border: Border(top: BorderSide(color: Colors.grey.shade200)),
                        borderRadius: const BorderRadius.vertical(bottom: Radius.circular(16)),
                      ),
                      child: Column(
                        crossAxisAlignment: CrossAxisAlignment.stretch,
                        children: [
                          Row(
                            mainAxisAlignment: MainAxisAlignment.spaceBetween,
                            children: [
                              const Text('Total Pembelian:', style: TextStyle(fontSize: 16, fontWeight: FontWeight.bold)),
                              Text(currencyFormatter.format(_calculateTotal()), style: const TextStyle(fontSize: 20, fontWeight: FontWeight.bold, color: AppColors.primary)),
                            ],
                          ),
                          const SizedBox(height: 16),
                          TextField(
                            controller: _paymentController,
                            keyboardType: TextInputType.number,
                            decoration: const InputDecoration(
                              labelText: 'Uang Diterima (Rp)',
                              border: OutlineInputBorder(),
                              prefixIcon: Icon(Icons.money),
                            ),
                            onChanged: (val) {
                              setState(() {
                                _uangDiterima = double.tryParse(val) ?? 0;
                              });
                            },
                          ),
                          const SizedBox(height: 16),
                          Row(
                            mainAxisAlignment: MainAxisAlignment.spaceBetween,
                            children: [
                              const Text('Kembali:', style: TextStyle(fontSize: 16)),
                              Text(
                                currencyFormatter.format((_uangDiterima - _calculateTotal()).clamp(0, double.infinity)), 
                                style: const TextStyle(fontSize: 18, fontWeight: FontWeight.bold, color: Colors.green),
                              ),
                            ],
                          ),
                          const SizedBox(height: 16),
                          ElevatedButton.icon(
                            onPressed: _cart.isEmpty || _uangDiterima < _calculateTotal() ? null : _processCheckout,
                            icon: const Icon(Icons.check_circle),
                            label: const Text('Bayar & Selesai', style: TextStyle(fontSize: 16)),
                            style: ElevatedButton.styleFrom(
                              backgroundColor: AppColors.accent,
                              foregroundColor: AppColors.textDark,
                              padding: const EdgeInsets.symmetric(vertical: 16),
                              shape: RoundedRectangleBorder(borderRadius: BorderRadius.circular(12)),
                            ),
                          ),
                        ],
                      ),
                    ),
                  ],
                ),
              ),
            ),
          ],
        ),
      ),
    );
  }
}
