import 'package:flutter/material.dart';
import 'package:petshopapp/models/grooming_booking_model.dart';
import 'package:petshopapp/services/grooming_service.dart';
import 'package:petshopapp/services/auth_service.dart';
import 'package:petshopapp/models/user_pet_model.dart';

class GroomingProvider with ChangeNotifier {
  final GroomingService _groomingService = GroomingService.instance;

  // Selected Service Details
  List<String> _selectedServices = [];
  double _selectedPrice = 0.0;
  
  // Pet Details
  List<UserPetModel> _selectedPets = [];

  // Location / Service Type
  bool _isHomeService = false;
  String _alamatLengkap = '';
  double? _latitude;
  double? _longitude;


  // Schedule Details
  DateTime? _selectedDate;
  String? _selectedTimeSlot;

  // Available slots logic
  List<String> _bookedSlots = [];
  bool _isLoadingSlots = false;

  // Getters
  List<String> get selectedServices => _selectedServices;
  double get selectedPrice => _selectedPrice;
  List<UserPetModel> get selectedPets => _selectedPets;
  bool get isHomeService => _isHomeService;
  String get alamatLengkap => _alamatLengkap;
  double? get latitude => _latitude;
  double? get longitude => _longitude;
  DateTime? get selectedDate => _selectedDate;
  String? get selectedTimeSlot => _selectedTimeSlot;
  List<String> get bookedSlots => _bookedSlots;
  bool get isLoadingSlots => _isLoadingSlots;

  // Setters
  void toggleService(String service, double price) {
    if (_selectedServices.contains(service)) {
      _selectedServices.remove(service);
      _selectedPrice -= price;
    } else {
      _selectedServices.add(service);
      _selectedPrice += price;
    }
    notifyListeners();
  }

  void updatePetsInfo(List<UserPetModel> pets) {
    _selectedPets = pets;
    notifyListeners();
  }

  void updateLocationInfo({required bool isHome, required String alamat, double? lat, double? lng}) {
    _isHomeService = isHome;
    _alamatLengkap = alamat;
    _latitude = lat;
    _longitude = lng;
    notifyListeners();
  }

  Future<void> selectDate(DateTime date) async {
    _selectedDate = date;
    _selectedTimeSlot = null; // Reset time slot when date changes
    _isLoadingSlots = true;
    notifyListeners();

    _bookedSlots = await _groomingService.getBookedSlots(date);
    
    _isLoadingSlots = false;
    notifyListeners();
  }

  void selectTimeSlot(String slot) {
    _selectedTimeSlot = slot;
    notifyListeners();
  }

  /// Finalize booking and save to Firestore
  Future<void> confirmBooking(String userId, String customerName, {String? buktiBayarUrl, required String metodePembayaran}) async {
    if (_selectedServices.isEmpty || _selectedDate == null || _selectedTimeSlot == null || _selectedPets.isEmpty) {
      throw Exception('Harap lengkapi data booking');
    }

    // Create a separate booking for each pet
    for (var pet in _selectedPets) {
      final booking = GroomingBookingModel(
        bookingId: '', // Auto-generated by Firestore
        userId: userId,
        customerName: customerName,
        petName: pet.name,
        petType: pet.type,
        serviceType: _selectedServices.join(', '),
        bookingDate: _selectedDate!,
        timeSlot: _selectedTimeSlot!,
        totalPrice: _selectedPrice, // Price per pet
        isHomeService: _isHomeService,
        alamatLengkap: _isHomeService ? _alamatLengkap : null,
        latitude: _isHomeService ? _latitude : null,
        longitude: _isHomeService ? _longitude : null,
        status: 'Pending',
        buktiBayarUrl: buktiBayarUrl,
        metodePembayaran: metodePembayaran,
        createdAt: DateTime.now(),
      );

      await _groomingService.createBooking(booking);
    }
    reset();
  }

  void reset() {
    _selectedServices = [];
    _selectedPrice = 0.0;
    _selectedPets = [];
    _isHomeService = false;
    _alamatLengkap = '';
    _latitude = null;
    _longitude = null;
    _selectedDate = null;
    _selectedTimeSlot = null;
    _bookedSlots = [];
    notifyListeners();
  }
}
