// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA7oTVULRo3y5sNG7vNltuqkVyKPb3kpsY',
    appId: '1:416976631560:web:772876747fe8f523c01ebd',
    messagingSenderId: '416976631560',
    projectId: 'pet-shop-app-115fb',
    authDomain: 'pet-shop-app-115fb.firebaseapp.com',
    databaseURL: 'https://pet-shop-app-115fb-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'pet-shop-app-115fb.firebasestorage.app',
    measurementId: 'G-WT304PSY43',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBf8ihru9s5lI2YiIVV70Kl9PHddDMnD_A',
    appId: '1:416976631560:android:bbe9849c878466d4c01ebd',
    messagingSenderId: '416976631560',
    projectId: 'pet-shop-app-115fb',
    databaseURL: 'https://pet-shop-app-115fb-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'pet-shop-app-115fb.firebasestorage.app',
  );
}
